# Generated by Django 5.2.1 on 2025-09-01 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Busqueda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_problema",
                    models.TextField(
                        help_text="El problema o consulta introducida por el usuario"
                    ),
                ),
                (
                    "resultado_llm",
                    models.JSONField(
                        help_text="Respuesta completa del LLM en formato JSON"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se realizó la búsqueda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que realizó la búsqueda",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Búsqueda",
                "verbose_name_plural": "Búsquedas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
