# Generated by Django 5.2.5 on 2025-09-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='modelo',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('cerebras', 'Cerebras')], default='gemini', help_text='Modelo LLM utilizado para la consulta', max_length=10),
        ),
    ]
