# Generated by Django 5.2.1 on 2025-10-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busqueda_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(choices=[('Corte', 'Corte'), ('Emprendimiento', 'Emprendimiento'), ('Empresa', 'Empresa'), ('Negocio', 'Negocio')], default='Negocio', help_text='Categoría de la consulta', max_length=20),
        ),
    ]
