# Generated by Django 5.2.1 on 2025-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_busqueda_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(choices=[('Automatización', 'Automatización'), ('Análisis de datos / predicción', 'Análisis de datos / predicción'), ('Procesamiento de texto', 'Procesamiento de texto'), ('Procesamiento de imágenes / video', 'Procesamiento de imágenes / video'), ('Procesamiento de audio / voz', 'Procesamiento de audio / voz'), ('Generación de contenido', 'Generación de contenido'), ('Recomendación / personalización', 'Recomendación / personalización'), ('Optimización / decisión inteligente', 'Optimización / decisión inteligente'), ('Asistentes conversacionales', 'Asistentes conversacionales')], default='Automatización', help_text='Categoría de la consulta', max_length=50),
        ),
        migrations.AlterField(
            model_name='busqueda',
            name='resultado_llm',
            field=models.JSONField(blank=True, help_text='Respuesta completa del LLM en formato JSON', null=True),
        ),
    ]
